export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS'


export const GET_ADD_CART_REQUEST = 'GET_ADD_CART_REQUEST'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE'
export const CREATE_ADD_CART = 'CREATE_ADD_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEMS'
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY'
export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_FAILURE = 'GET_SINGLE_PRODUCT_FAILURE'

export const CLEAR_CART = 'CLEAR_CART'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'